server_blocks:
  - name: server # 服务名称
    protocol: http  # 协议类型
    port: 7256  # 监听端口
    max_body_size: 4 # 最大请求体大小单位MB
    locations:  # 路由配置
      - path: /api/.+ # 路由路径
        proxy_pass: # 反向代理配置
          - schema: http
            host: 127.0.0.1
            port: 5000
            weight: 1 # 权重
          - schema: http
            host: 127.0.0.1
            port: 5001
            weight: 2
      - path: /.* # 路由路径
        root: html  # 静态文件根目录
